<definitions name="FraseService"
   targetNamespace="http://www.examples.com/wsdl/FraseService.wsdl"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="http://www.examples.com/wsdl/FraseService.wsdl"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
   <message name="frasedeldiaRequest">
    </message>
  
   <message name="frasedeldiaResponse">
      <part name="frase" type="xsd:string"/>
   </message>

   <portType name="Frase_PortType">
      <operation name="frasedeldia">
         <input message="tns:frasedeldiaRequest"/>
         <output message="tns:frasedeldiaResponse"/>
      </operation>
   </portType>

   <binding name="Frase_Binding" type="tns:Frase_PortType">
      <soap:binding style="rpc"
         transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="frasedeldia">
         <soap:operation soapAction="frasedeldia"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:Fraseservice"
               use="encoded"/>
         </input>
    
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:Fraseservice"
               use="encoded"/>
         </output>
      </operation>
   </binding>

   <service name="Frase_Service">
      <documentation>WSDL File for FraseService</documentation>
      <port binding="tns:Frase_Binding" name="Frase_Port">
         <soap:address
            location="http://www.examples.com/frasedeldia/" />
      </port>
   </service>
</definitions>