CREATE TABLE `categories` (`id`	INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,`name`	VARCHAR(100) NOT NULL);

CREATE  TABLE wsdls (`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `url` VARCHAR(200) NOT NULL, `category_id` INT(11) NOT NULL, `reputation` INT(11)  DEFAULT 0, `response` INT(11)  DEFAULT 99999, `availability` INT(11) DEFAULT 0);
