package UI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

public class WSDLUI extends javax.swing.JInternalFrame {

    private DefaultTableModel wsdlDefault;

    public WSDLUI() {
        initComponents();
        wsdlDefault = (DefaultTableModel) tableWSDL.getModel();
    }

    public void setActionListener(ActionListener lis) {
        this.save.addActionListener(lis);
        this.delete.addActionListener(lis);
        this.newWSDL.addActionListener(lis);
        this.edit.addActionListener(lis);
    }

    public void clickNew() {
        clear();
        clickEdit();
    }

    public void clickEdit() {
        newWSDL.setEnabled(false);
        name.setEnabled(true);
        url.setEnabled(true);
        cbCategory.setEnabled(true);
        save.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);
        
    }

    public void enableFields(boolean b) {
        name.setEnabled(b);
        url.setEnabled(b);
        cbCategory.setEnabled(b);
    }

    public void clear() {
        id.setText("");
        name.setText("");
        url.setText("");
        cbCategory.removeAll();
        cbCategory.setSelectedIndex(-1);
    }

    public void clickSave() {
        clear();
        name.setEnabled(false);
        newWSDL.setEnabled(true);
        url.setEnabled(false);
        cbCategory.setEnabled(false);
        save.setEnabled(false);
        edit.setEnabled(false);
        delete.setEnabled(false);
    }

    public void wsdlSelected(boolean b) {
        if (!b) {
            clear();
        }
        edit.setEnabled(b);
        delete.setEnabled(b);
    }

    public DefaultTableModel getWsdlDefault() {
        return wsdlDefault;
    }

    public JComboBox<String> getCbCategory() {
        return cbCategory;
    }

    public JButton getDelete() {
        return delete;
    }

    public JButton getEdit() {
        return edit;
    }

    public JTextField getId() {
        return id;
    }

    public JTextField getNameWSDL() {
        return name;
    }

    public JButton getNewWSDL() {
        return newWSDL;
    }

    public JButton getSave() {
        return save;
    }

    public JTextField getSearch() {
        return search;
    }

    public JTable getTableWSDL() {
        return tableWSDL;
    }

    public JTextField getUrl() {
        return url;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroolClientes = new javax.swing.JScrollPane();
        panelEnteroClientes = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableWSDL = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        delete.setIcon(new ImageIcon(WSDLUI.class.getResource("/UI/Icons/borrar.png")));
        newWSDL = new javax.swing.JButton();
        newWSDL.setIcon(new ImageIcon(WSDLUI.class.getResource("/UI/Icons/nuevo.png")));
        edit = new javax.swing.JButton();
        edit.setIcon(new ImageIcon(WSDLUI.class.getResource("/UI/Icons/modificar.png")));
        save = new javax.swing.JButton();
        save.setIcon(new ImageIcon(WSDLUI.class.getResource("/UI/Icons/guardar.png")));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Management wsdl");
        setPreferredSize(new java.awt.Dimension(876, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        scroolClientes.setName(""); // NOI18N
        scroolClientes.setPreferredSize(new java.awt.Dimension(855, 480));
        scroolClientes.setRequestFocusEnabled(false);

        panelEnteroClientes.setPreferredSize(new java.awt.Dimension(825, 475));

        panelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WSDL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 15))); // NOI18N

        tableWSDL.setAutoCreateRowSorter(true);
        tableWSDL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Url", "Categoty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableWSDL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableWSDL);

        search.setToolTipText("Búsqueda personalizada");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(search)
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WSDL data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 15))); // NOI18N

        name.setEnabled(false);

        jLabel1.setText("Name");

        id.setEnabled(false);

        jLabel3.setText("ID");

        jLabel4.setText("Url");

        url.setEnabled(false);

        jLabel2.setText("Category");
        cbCategory.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(name)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(url)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        delete.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        delete.setToolTipText("Delete");
        delete.setEnabled(false);
        delete.setPreferredSize(new java.awt.Dimension(55, 33));
        jPanel4.add(delete);

        newWSDL.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        newWSDL.setToolTipText("New");
        newWSDL.setPreferredSize(new java.awt.Dimension(55, 33));
        jPanel4.add(newWSDL);

        edit.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        edit.setToolTipText("Edit");
        edit.setEnabled(false);
        edit.setPreferredSize(new java.awt.Dimension(55, 33));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel4.add(edit);

        save.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        save.setToolTipText("Save");
        save.setEnabled(false);
        save.setPreferredSize(new java.awt.Dimension(55, 33));
        jPanel4.add(save);

        javax.swing.GroupLayout panelEnteroClientesLayout = new javax.swing.GroupLayout(panelEnteroClientes);
        panelEnteroClientes.setLayout(panelEnteroClientesLayout);
        panelEnteroClientesLayout.setHorizontalGroup(
            panelEnteroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnteroClientesLayout.createSequentialGroup()
                .addGroup(panelEnteroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelEnteroClientesLayout.setVerticalGroup(
            panelEnteroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnteroClientesLayout.createSequentialGroup()
                .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scroolClientes.setViewportView(panelEnteroClientes);
        panelEnteroClientes.getAccessibleContext().setAccessibleName("");
        panelEnteroClientes.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(scroolClientes);
        scroolClientes.getAccessibleContext().setAccessibleName("Panel");
        scroolClientes.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("clienteGui");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JButton newWSDL;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelEnteroClientes;
    private javax.swing.JButton save;
    private javax.swing.JScrollPane scroolClientes;
    private javax.swing.JTextField search;
    private javax.swing.JTable tableWSDL;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables

}
